#!/bin/bash

# Update for your admin password
AdminPassword=ganuTHa8

# Create a resource group.
#az group create --name myResourceGroup --location westeurope

# Create a virtual network.
#az network vnet create --resource-group myResourceGroup --name myVnet --subnet-name mySubnet

# Create a public IP address.
#az network public-ip create --resource-group UberDuber --name UberPublicIP

# Create a network security group.
az network nsg create --resource-group UberCanada --name UberDuberNetSecGrp
#az network nsg create --resource-group "UberDuber" --name "UberDuberNetSecGrp" --verbose
# Create a virtual network card and associate with public IP address and NSG.
az network nic create \
  --resource-group UberDuber \
  --name UberDuberNic \
  --vnet-name UberDuberSubnet \
  --subnet UberDuber \
  --network-security-group UberDuberNetSecGrp \
  --public-ip-address UberDuberIP

# Create a virtual machine. 
az vm create \
    --resource-group UberDuber \
    --name UberDuberVM \
    --location eastus \
    --nics UberDuberNic \
    --image win2016datacenter \
    --admin-username UberAdmin \
    --admin-password $AdminPassword

# Open port 3389 to allow RDP traffic to host.
az vm open-port --port 3389 --resource-group UberDuber --name UberDuberVM